### PR TITLE
Fix issue with non-printable characters

### LINKED ISSUE #16: Unrecognized characters in search input
A bug in handling input from the user in the search makes "weird" unicode characters to appear.

## Steps to reproduce

There are two methods of triggering this bug that I know of

### Method 1 (works in multiple choice and single choice)

* Click on the select (you now should be able to type & the dropdown appears)
* Press Return (the first option should be selected)
* Type Uppercase "E" by holding `Shift` + `E`

A "" character appears in the input.

### Method 2

* Click on the select (you now should be able to type & the dropdown appears)
* Hold `Ctrl` and click on the input again, release `Ctrl` after click

A "" character appears in the input.

## Code description & solution

The bug is triggered in the `mainClick()` method. Every `keyCode` of every event that goes into this method gets converted to a string by `String.fromCharCode()` and put into the input, without verification.

Some keyup and keydown events, such as arrows, key-combos and special non-printable characters can be there as well. Fortunatelly, `KeyboardEvent` class contains a `.charCode`, that when used on onkeydown or onkeyup events returns "0".

I've opened up a PR that fixes this issue: https://github.com/psilospore/ng-next-select/pull/15

### PR DESCRIPTION
**Pull request by samupl**
This PR fixes #16.
I've also removed a couple of redundant whitespaces around function declarations.

### CODE REVIEW

**Review by jbszczepaniak — APPROVED** [review]
Despite lack of unit tests (which is the problem in the entire project) this looks good.

**Comment by psilospore** [comment]
Looks good to me. Thanks for the submission! I'll try to push sometime soon and notify you all. @jedruniu I created https://github.com/psilospore/ng-next-select/issues/17 if you know anyone willing to contribute.

**Comment by samupl** [comment]
I forgot to increase the version in `package.json`. Could you please do that & publish a new version to npm?

**Comment by psilospore** [comment]
Published as `1.4.0` thank you 🥇

**Comment by samupl** [comment]
Are you sure it's published? On https://www.npmjs.com/package/ng-next-select the latest version is `1.3.13`, which still contains this bug.

**Pull request merged**
